version: 2
before:
  hooks:
    - go mod tidy
    - ./scripts/prepare-release.sh {{ .Version }}
builds:
- env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64
  ignore:
    - goos: darwin
      goarch: '386'
  binary: '{{ .ProjectName }}_v{{ .Version }}'
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  files:
    - terraform-registry-manifest.json
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
  extra_files:
    - glob: terraform-registry-manifest.json
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  mode: append
  extra_files:
    - glob: terraform-registry-manifest.json
    - dst: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
      src: terraform-registry-manifest.json
changelog:
  disable: true
